// Generated by https://quicktype.io

export interface UserI {
    access_token: string;
    refresh_token: string;
    user:         User;
}

export interface User {
    createAt: string;
    updateAt: string;
    id:       number;
    email:    string;
}

// auth register
export interface RegisterResponse {
    email:    string;
    customer: Customer;
    role:     Role;
    source:   null;
    createAt: Date;
    updateAt: Date;
    id:       number;
}

export interface Customer {
    name:     string;
    lastname: string;
    phone:    string;
    createAt: Date;
    updateAt: Date;
    id:       number;
}

export interface Role {
    createAt:    Date;
    updateAt:    Date;
    id:          number;
    name:        string;
    description: string;
}
